### ISSUE TITLE
NoReverseMatch at /admin/django_news/entry/add/

### ISSUE THREAD

**Issue by egorsmkv** [bzzzzzz/django-simple-news-app#3]
In admin panel i get this error:

```shell
Reverse for 'ckeditor_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/django_news/entry/add/
Django Version:	1.10.3
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'ckeditor_upload' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location:	/usr/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 392
Python Executable:	/usr/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/egor/MyProjects/cashback_project',
 '/usr/lib/python3.5/site-packages/inlinestyler-0.2.0-py3.5.egg',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-linux',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5/site-packages']
```

**Comment by egorsmkv** [comment]
@bzzzzzz ping

**Comment by bzzzzzz** [comment]
Hello.

Sorry for not responding for too long, I've been on vacation away from my laptop.
It seems that you're getting this error because you have misconfigured django_ckeditor. Please read https://github.com/django-ckeditor/django-ckeditor#required-for-using-widget-with-file-upload and check that CKEDITOR_UPLOAD_PATH setting is correct and you have provided valid urls.py for this app. If it does not help you, please post here parts of your settings.py and urls.py files, connected to django-simple-news-app so I can reproduce this error

**Comment by egorsmkv** [comment]
Понял. Добавьте, пожалуйста, в readme секцию о полной установке модуля.
